// Lista de especialidades de parceiros centralizada
export const partnerSpecialties = [
  "Academia",
  "Açougue",
  "Adega",
  "Advogado",
  "Arquiteto",
  "Atleta/Personalidade",
  "Auto Center",
  "Auto Peças",
  "Barbearia",
  "Cafeteria",
  "Clínica",
  "Clínica Estética",
  "Clube Esportivo/Associação",
  "Contador",
  "Consultor",
  "Corretor",
  "Curso Livre/Profissionalizante",
  "Dentista",
  "Despachante",
  "Eletricista",
  "Emissora",
  "Engenharia",
  "Encanador",
  "Escola de Idiomas",
  "Escola/Colégio",
  "Esteticista",
  "Faculdade",
  "Farmácia",
  "Fisioterapeuta",
  "Hamburgueria",
  "Indústria",
  "Influenciador/Criador de Conteúdo",
  "Jornal",
  "Laboratório/Clínica Popular",
  "Lanchonete",
  "Lava Rápido",
  "Locadora de Veículos",
  "Loja de Calçados",
  "Loja de Cama, Mesa e Banho",
  "Loja de Eletro",
  "Loja de Móveis",
  "Loja de Roupas",
  "Loja Infantil/Brinquedos",
  "Marcenaria/Serralheria",
  "Material de Construção",
  "Médico",
  "Nutricionista",
  "Oficina Mecânica",
  "Ótica",
  "ONG/Instituição Parceira",
  "Padaria",
  "Personal Trainer",
  "Pet Shop",
  "Piscinas",
  "Posto de Combustível",
  "Psicólogo",
  "Restaurante",
  "Salão de Beleza",
  "Sorveteria",
  "Supermercado",
  "Veterinário",
] as const;

export type PartnerSpecialty = typeof partnerSpecialties[number];

export const SPECIALTY_OTHER = "__other__";
