// Lista de especialidades de parceiros centralizada
export const partnerSpecialties = [
  "Academia",
  "Açougue",
  "Advogado",
  "Agropecuária",
  "Arquiteto",
  "Atleta",
  "Auto peças",
  "Cafeteria",
  "Clínica",
  "Clube",
  "Comércio",
  "Contador",
  "Consultor",
  "Corretor",
  "Dentista",
  "Despachante",
  "Emissora",
  "Empresa",
  "Escola/Colégio",
  "Esteticista",
  "Faculdade",
  "Farmácia",
  "Fisioterapeuta",
  "Hamburgueria",
  "Hotel/Pousada",
  "Imobiliária",
  "Indústria",
  "Influencer",
  "Jornal",
  "Lanchonete",
  "Lava Rápido",
  "Loja de brinquedos",
  "Loja de calçados",
  "Loja de cama, mesa e banho",
  "Loja de eletro",
  "Loja de móveis",
  "Loja de roupas",
  "Material de Construção",
  "Mecânico",
  "Médico",
  "Nutricionista",
  "Padaria",
  "Personal Trainer",
  "Personalidade",
  "Pet Shop",
  "Piscinas",
  
  "Psicólogo",
  "Restaurante",
  "Sorveteria",
  "Supermercado",
  "Veterinário",
] as const;

export type PartnerSpecialty = typeof partnerSpecialties[number];

export const SPECIALTY_OTHER = "__other__";
